/* The following code was generated by JFlex 1.4.3 on 5/05/22 10:52 AM */

package dao;
import static dao.Tokens.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 5/05/22 10:52 AM from the specification file
 * <tt>C:/Users/OTTONIEL CAMPOS/Desktop/Analizador Lexico/AnalizadorLexico/AnalizadorLexico/src/codigo/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\35\2\0\1\3\22\0\1\3\7\0\1\36\1\37"+
    "\1\43\1\41\1\3\1\42\1\0\1\34\12\2\3\0\1\40\3\0"+
    "\32\1\1\46\1\0\1\47\1\0\1\1\1\0\1\4\1\5\1\11"+
    "\1\22\1\16\1\17\1\24\1\21\1\14\1\1\1\26\1\23\1\32"+
    "\1\13\1\12\1\25\1\1\1\10\1\6\1\7\1\15\1\31\1\20"+
    "\1\33\1\27\1\30\1\44\1\0\1\45\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\20\2\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\25\2\1\20\10\2\1\20\7\2\1\4\1\0"+
    "\25\2\1\20\20\2\1\0\26\2\1\3\14\2\1\20"+
    "\31\2";

  private static int [] zzUnpackAction() {
    int [] result = new int[172];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\50\0\120\0\170\0\240\0\310\0\360\0\u0118"+
    "\0\u0140\0\u0168\0\u0190\0\u01b8\0\u01e0\0\u0208\0\u0230\0\u0258"+
    "\0\u0280\0\u02a8\0\u02d0\0\u02f8\0\u0320\0\u0348\0\u0370\0\50"+
    "\0\50\0\50\0\50\0\50\0\50\0\50\0\50\0\50"+
    "\0\u0398\0\u03c0\0\u03e8\0\u0410\0\u0438\0\u0460\0\u0488\0\u04b0"+
    "\0\u04d8\0\u0500\0\u0528\0\u0550\0\u0578\0\u05a0\0\u05c8\0\u05f0"+
    "\0\u0618\0\u0640\0\u0668\0\u0690\0\u06b8\0\120\0\u06e0\0\u0708"+
    "\0\u0730\0\u0758\0\u0780\0\u07a8\0\u07d0\0\u07f8\0\u0820\0\u0848"+
    "\0\u0870\0\u0898\0\u08c0\0\u08e8\0\u0910\0\u0938\0\u0960\0\u0988"+
    "\0\u09b0\0\u09d8\0\u0a00\0\u0a28\0\u0a50\0\u0a78\0\u0aa0\0\u0ac8"+
    "\0\u0af0\0\u0b18\0\u0b40\0\u0b68\0\u0b90\0\u0bb8\0\u0be0\0\u0c08"+
    "\0\u0c30\0\u0c58\0\u0c80\0\u0ca8\0\u0cd0\0\u0cf8\0\u0d20\0\u0d48"+
    "\0\u0d70\0\u0d98\0\u0dc0\0\u0de8\0\u0e10\0\u0e38\0\u0e60\0\u0e88"+
    "\0\u0eb0\0\u0ed8\0\u0f00\0\u0f28\0\u0f50\0\u0f78\0\u0fa0\0\u0fc8"+
    "\0\u0ff0\0\u1018\0\u1040\0\u1068\0\u1090\0\u10b8\0\u10e0\0\u1108"+
    "\0\u1130\0\u1158\0\u1180\0\u11a8\0\u11d0\0\u11f8\0\u1220\0\u1248"+
    "\0\u1270\0\u1298\0\u12c0\0\u12e8\0\u1310\0\50\0\u1338\0\u1360"+
    "\0\u1388\0\u13b0\0\u13d8\0\u1400\0\u1428\0\u1450\0\u1478\0\u14a0"+
    "\0\u14c8\0\u14f0\0\u1518\0\u1540\0\u1568\0\u1590\0\u15b8\0\u15e0"+
    "\0\u1608\0\u1630\0\u1658\0\u1680\0\u16a8\0\u16d0\0\u16f8\0\u1720"+
    "\0\u1748\0\u1770\0\u1798\0\u17c0\0\u17e8\0\u1810\0\u1838\0\u1860"+
    "\0\u1888\0\u18b0\0\u18d8\0\u1900";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[172];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\3\1\14\1\15\1\3\1\16\1\17"+
    "\1\20\1\3\1\21\1\22\1\23\1\24\3\3\1\25"+
    "\2\3\1\26\1\5\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\51\0\2\3\1\0"+
    "\30\3\16\0\1\4\50\0\1\5\31\0\1\5\13\0"+
    "\2\3\1\0\1\3\1\41\1\42\1\3\1\43\23\3"+
    "\15\0\2\3\1\0\4\3\1\44\1\3\1\45\14\3"+
    "\1\46\4\3\15\0\2\3\1\0\3\3\1\47\5\3"+
    "\1\50\2\3\1\51\1\52\5\3\1\53\4\3\15\0"+
    "\2\3\1\0\4\3\1\54\10\3\1\55\12\3\15\0"+
    "\2\3\1\0\12\3\1\56\15\3\15\0\2\3\1\0"+
    "\1\57\5\3\1\60\6\3\1\61\1\3\1\62\10\3"+
    "\15\0\2\3\1\0\1\63\11\3\1\64\15\3\15\0"+
    "\2\3\1\0\7\3\1\65\3\3\1\66\12\3\1\67"+
    "\1\3\15\0\2\3\1\0\7\3\1\70\7\3\1\71"+
    "\7\3\1\72\15\0\2\3\1\0\6\3\1\73\1\3"+
    "\1\74\6\3\1\75\10\3\15\0\2\3\1\0\15\3"+
    "\1\76\12\3\15\0\2\3\1\0\6\3\1\77\3\3"+
    "\1\100\15\3\15\0\2\3\1\0\6\3\1\101\21\3"+
    "\15\0\2\3\1\0\6\3\1\102\21\3\15\0\2\3"+
    "\1\0\1\103\3\3\1\104\4\3\1\105\16\3\15\0"+
    "\2\3\1\0\6\3\1\106\21\3\50\0\1\107\55\0"+
    "\1\110\6\0\2\3\1\0\2\3\1\111\25\3\15\0"+
    "\2\3\1\0\2\3\1\112\25\3\15\0\2\3\1\0"+
    "\20\3\1\113\7\3\15\0\2\3\1\0\12\3\1\114"+
    "\15\3\15\0\2\3\1\0\6\3\1\115\21\3\15\0"+
    "\2\3\1\0\3\3\1\116\24\3\15\0\2\3\1\0"+
    "\1\117\3\3\1\120\23\3\15\0\2\3\1\0\21\3"+
    "\1\121\6\3\15\0\2\3\1\0\10\3\1\122\17\3"+
    "\15\0\2\3\1\0\6\3\1\123\21\3\15\0\2\3"+
    "\1\0\7\3\1\124\20\3\15\0\2\3\1\0\1\125"+
    "\22\3\1\66\4\3\15\0\2\3\1\0\4\3\1\126"+
    "\1\3\1\127\1\3\1\113\17\3\15\0\2\3\1\0"+
    "\3\3\1\130\24\3\15\0\2\3\1\0\2\3\1\116"+
    "\1\131\24\3\15\0\2\3\1\0\7\3\1\132\20\3"+
    "\15\0\2\3\1\0\1\73\27\3\15\0\2\3\1\0"+
    "\1\133\27\3\15\0\2\3\1\0\3\3\1\134\24\3"+
    "\15\0\2\3\1\0\14\3\1\66\13\3\15\0\2\3"+
    "\1\0\2\3\1\135\1\136\24\3\15\0\2\3\1\0"+
    "\21\3\1\137\6\3\15\0\2\3\1\0\11\3\1\140"+
    "\16\3\15\0\2\3\1\0\2\3\1\116\25\3\15\0"+
    "\2\3\1\0\3\3\1\141\24\3\15\0\2\3\1\0"+
    "\4\3\1\66\23\3\15\0\2\3\1\0\7\3\1\142"+
    "\20\3\15\0\2\3\1\0\6\3\1\143\21\3\15\0"+
    "\2\3\1\0\10\3\1\144\17\3\15\0\2\3\1\0"+
    "\11\3\1\145\16\3\15\0\2\3\1\0\13\3\1\146"+
    "\14\3\15\0\2\3\1\0\7\3\1\147\20\3\15\0"+
    "\2\3\1\0\3\3\1\150\24\3\15\0\2\3\1\0"+
    "\5\3\1\151\22\3\15\0\2\3\1\0\6\3\1\152"+
    "\1\3\1\153\17\3\15\0\2\3\1\0\1\3\1\154"+
    "\26\3\15\0\2\3\1\0\10\3\1\155\6\3\1\156"+
    "\10\3\14\0\35\107\1\0\12\107\2\0\1\157\46\0"+
    "\2\3\1\0\3\3\1\160\24\3\15\0\2\3\1\0"+
    "\12\3\1\123\15\3\15\0\2\3\1\0\2\3\1\66"+
    "\25\3\15\0\2\3\1\0\1\161\27\3\15\0\2\3"+
    "\1\0\17\3\1\162\10\3\15\0\2\3\1\0\12\3"+
    "\1\66\15\3\15\0\2\3\1\0\3\3\1\163\24\3"+
    "\15\0\2\3\1\0\10\3\1\164\17\3\15\0\2\3"+
    "\1\0\12\3\1\73\15\3\15\0\2\3\1\0\3\3"+
    "\1\131\24\3\15\0\2\3\1\0\4\3\1\165\23\3"+
    "\15\0\2\3\1\0\5\3\1\166\22\3\15\0\2\3"+
    "\1\0\7\3\1\167\20\3\15\0\2\3\1\0\6\3"+
    "\1\64\21\3\15\0\2\3\1\0\14\3\1\113\13\3"+
    "\15\0\2\3\1\0\11\3\1\170\16\3\15\0\2\3"+
    "\1\0\5\3\1\171\22\3\15\0\2\3\1\0\2\3"+
    "\1\165\1\172\24\3\15\0\2\3\1\0\2\3\1\113"+
    "\25\3\15\0\2\3\1\0\10\3\1\173\17\3\15\0"+
    "\2\3\1\0\3\3\1\174\24\3\15\0\2\3\1\0"+
    "\12\3\1\175\15\3\15\0\2\3\1\0\6\3\1\123"+
    "\10\3\1\176\10\3\15\0\2\3\1\0\26\3\1\66"+
    "\1\3\15\0\2\3\1\0\12\3\1\177\15\3\15\0"+
    "\2\3\1\0\1\200\27\3\15\0\2\3\1\0\1\165"+
    "\27\3\15\0\2\3\1\0\17\3\1\116\10\3\15\0"+
    "\2\3\1\0\1\3\1\144\26\3\15\0\2\3\1\0"+
    "\1\201\27\3\15\0\2\3\1\0\20\3\1\66\7\3"+
    "\15\0\2\3\1\0\6\3\1\66\21\3\15\0\2\3"+
    "\1\0\22\3\1\202\5\3\15\0\2\3\1\0\3\3"+
    "\1\203\24\3\15\0\2\3\1\0\25\3\1\204\2\3"+
    "\15\0\2\3\1\0\17\3\1\163\10\3\15\0\2\3"+
    "\1\0\16\3\1\66\11\3\15\0\2\3\1\0\1\205"+
    "\27\3\16\0\1\157\34\0\1\206\11\0\2\3\1\0"+
    "\4\3\1\207\23\3\15\0\2\3\1\0\22\3\1\66"+
    "\5\3\15\0\2\3\1\0\12\3\1\210\15\3\15\0"+
    "\2\3\1\0\10\3\1\211\17\3\15\0\2\3\1\0"+
    "\5\3\1\212\22\3\15\0\2\3\1\0\3\3\1\66"+
    "\24\3\15\0\2\3\1\0\15\3\1\213\12\3\15\0"+
    "\2\3\1\0\2\3\1\214\25\3\15\0\2\3\1\0"+
    "\4\3\1\215\23\3\15\0\2\3\1\0\15\3\1\66"+
    "\12\3\15\0\2\3\1\0\10\3\1\216\17\3\15\0"+
    "\2\3\1\0\25\3\1\116\2\3\15\0\2\3\1\0"+
    "\1\217\27\3\15\0\2\3\1\0\4\3\1\220\23\3"+
    "\15\0\2\3\1\0\12\3\1\221\15\3\15\0\2\3"+
    "\1\0\7\3\1\222\20\3\15\0\2\3\1\0\17\3"+
    "\1\223\10\3\15\0\2\3\1\0\11\3\1\224\16\3"+
    "\15\0\2\3\1\0\1\225\27\3\15\0\2\3\1\0"+
    "\12\3\1\226\15\3\15\0\2\3\1\0\1\46\27\3"+
    "\15\0\2\3\1\0\3\3\1\76\24\3\15\0\2\3"+
    "\1\0\1\227\27\3\15\0\2\3\1\0\1\215\27\3"+
    "\15\0\2\3\1\0\5\3\1\66\22\3\15\0\2\3"+
    "\1\0\3\3\1\230\24\3\15\0\2\3\1\0\4\3"+
    "\1\231\23\3\15\0\2\3\1\0\10\3\1\232\17\3"+
    "\15\0\2\3\1\0\7\3\1\66\20\3\15\0\2\3"+
    "\1\0\7\3\1\233\20\3\15\0\2\3\1\0\7\3"+
    "\1\234\20\3\15\0\2\3\1\0\13\3\1\235\14\3"+
    "\15\0\2\3\1\0\26\3\1\236\1\3\15\0\2\3"+
    "\1\0\16\3\1\113\11\3\15\0\2\3\1\0\17\3"+
    "\1\237\10\3\15\0\2\3\1\0\17\3\1\165\10\3"+
    "\15\0\2\3\1\0\20\3\1\116\7\3\15\0\2\3"+
    "\1\0\5\3\1\240\22\3\15\0\2\3\1\0\5\3"+
    "\1\165\22\3\15\0\2\3\1\0\13\3\1\241\14\3"+
    "\15\0\2\3\1\0\6\3\1\242\21\3\15\0\2\3"+
    "\1\0\12\3\1\243\15\3\15\0\2\3\1\0\11\3"+
    "\1\116\16\3\15\0\2\3\1\0\5\3\1\244\22\3"+
    "\15\0\2\3\1\0\1\245\27\3\15\0\2\3\1\0"+
    "\12\3\1\246\15\3\15\0\2\3\1\0\23\3\1\66"+
    "\4\3\15\0\2\3\1\0\3\3\1\247\24\3\15\0"+
    "\2\3\1\0\21\3\1\66\6\3\15\0\2\3\1\0"+
    "\7\3\1\250\20\3\15\0\2\3\1\0\7\3\1\165"+
    "\20\3\15\0\2\3\1\0\12\3\1\251\15\3\15\0"+
    "\2\3\1\0\5\3\1\116\22\3\15\0\2\3\1\0"+
    "\7\3\1\252\20\3\15\0\2\3\1\0\12\3\1\155"+
    "\15\3\15\0\2\3\1\0\10\3\1\253\17\3\15\0"+
    "\2\3\1\0\6\3\1\254\21\3\15\0\2\3\1\0"+
    "\3\3\1\113\24\3\15\0\2\3\1\0\24\3\1\247"+
    "\3\3\15\0\2\3\1\0\13\3\1\66\14\3\14\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6440];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\25\1\11\11\47\1\1\0\46\1\1\0"+
    "\26\1\1\11\46\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[172];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 114) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 15: 
          { return Ccorchetes;
          }
        case 17: break;
        case 1: 
          { return ERROR;
          }
        case 18: break;
        case 5: 
          { return Division;
          }
        case 19: break;
        case 9: 
          { return Suma;
          }
        case 20: break;
        case 8: 
          { return Igual;
          }
        case 21: break;
        case 16: 
          { lexeme=yytext(); return Reservadas;
          }
        case 22: break;
        case 13: 
          { return Cllaves;
          }
        case 23: break;
        case 11: 
          { return Multiplicacion;
          }
        case 24: break;
        case 14: 
          { return Acorchetes;
          }
        case 25: break;
        case 3: 
          { lexeme=yytext(); return Numero;
          }
        case 26: break;
        case 12: 
          { return Allaves;
          }
        case 27: break;
        case 10: 
          { return Resta;
          }
        case 28: break;
        case 6: 
          { return Aparentesis;
          }
        case 29: break;
        case 4: 
          { /*Ignore*/
          }
        case 30: break;
        case 2: 
          { lexeme=yytext(); return Identificador;
          }
        case 31: break;
        case 7: 
          { return CParentesis;
          }
        case 32: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
